# This workflow will do nothing

name: LoL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Trying!
      run: echo Hello WorlD!
